# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2"

required_plugins = %w( vagrant-vbguest )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|

  config.vm.box = "nrel/CentOS-6.5-x86_64"
  config.ssh.forward_agent = true
  config.ssh.shell = "bash -l" 
  
  config.vm.hostname = "CentosServer65"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.99"

  config.vm.synced_folder "../ansible", "/ansible"
  
  config.vm.synced_folder "../shared", "/home/vagrant/shared",
    owner: 'vagrant',
    group: 'vagrant',
    mount_options: ['dmode=777', 'fmode=666']

  config.vm.synced_folder "../sites", "/var/www/html/"
  
  config.vm.provision :shell, path: "shell/vagrant_main_provision.sh"
end
