---
- name: Server Config Java
  hosts: "webservers"
  become: true
  become_user: root
  vars_files:
    - vars/main.yml

  roles:
    - { role: geerlingguy.java }
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

    - { role: geerlingguy.nodejs }

    - { role: geerlingguy.mysql }
    
    - { role: geerlingguy.git }

